### ISSUE TITLE
Word (.docx) output support

### ISSUE THREAD

**Issue by shunkosa** [shunkosa/sfdx-flowdoc-plugin#6]
Support .docx output. 

## Tasks
- [x] Add draft command
- [x] Fix output layout
- [x] Update README.md (including screenshot)
- [x] Publish

## Expected usage
`sfdx flowdoc:docx:generate Process_API_Name`

## Approach
Library: https://docx.js.org/
Currrently, the program is strongly dependent on 'pdfmake'. it should be refactored to generate human-readable JSON first and then pdf and docx command create each document based on it.
